spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: gims
      username: app
      password: password
      authentication-database: admin

server:
  port: 8081

logging:
  level:
    com:
      allianceair:
        gims: TRACE